name: ct-classifier-dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # -- PROD -- #
  - python=3.11
  - pytorch=2.6.0
  - polars-lts-cpu
  - ruamel.yaml
  - accelerate
  - pydantic
  - typer
  - fsspec
  - joblib
  - scikit-learn
  - numpy
  - transformers>=4.40
  - tqdm
  - xgboost
  - loguru
  - matplotlib
  # -- PROD.PIP -- #
  - pip
  - pip:
    - -e .
    - torchdr
    - safetensors